[tool.poetry]
name = "ttflow"
version = "0.1.0"
description = "simple workflow engine"
authors = ["moajo <mimirosiasd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fire = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ttflow = "ttflow.cli:main"
